### ISSUE TITLE
Match 21.10 Workspace Picker to the COSMIC design

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-workspaces#1]
Styling has been slightly updated from 21.04
![image](https://user-images.githubusercontent.com/3430283/133832620-c82d9e96-dd59-43c6-8d38-5cfe5990f878.png)

See more mockups here: https://www.figma.com/file/6vzaICveLGHnUqZrZ8XVrn/Workspaces-search?node-id=296%3A22007

**Comment by jackpot51** [comment]
Moving to vertical-overview, since the code for the workspace picker is there.

**Comment by WatchMkr** [comment]
Workspace picker corner radii and styling also here: https://www.figma.com/file/6vzaICveLGHnUqZrZ8XVrn/Workspaces-search?node-id=116%3A1991

**Comment by ids1024** [comment]
This is improved in the current `master_impish` code, though it could still use more tweaks.

**Comment by WatchMkr** [comment]
Cool, reassigning to @isantop for final touches.

**Comment by fouadzouraibi** [comment]
i don't know why there is a search in workspace overview, it has no meaning for me since we all used to super and type all i want to find, and swipe to see the workspace. But hey its good for others i guess (maybe add hide search in overview). 
I was wondering about the DoT (DNS over TLS) support ? and the New gnome app Remote desktop Control ?

**Comment by ajstrongdev** [comment]
> i don't know why there is a search in workspace overview, it has no meaning for me since we all used to super and type all i want to find, and swipe to see the workspace. But hey its good for others i guess (maybe add hide search in overview). I was wondering about the DoT (DNS over TLS) support ? and the New gnome app Remote desktop Control ?

I have a feeling it's to make the transition from GNOME to COSMIC easier. I'm very used to GNOME 40 at the moment however I'm looking to move to Pop!_OS once 21.10 has released and one thing I am wishing is that I could have workspaces + launcher combined so that I would be able to press super and type for the application I want, whilst still getting my workspace overview.

**Comment by WatchMkr** [comment]
The reason for search in workspaces is the scenario where a user spreads their windows to see what's open, doesn't have what they need, and can quickly launch it from there. We're unifying the launcher experience across the OS.

**Comment by ajstrongdev** [comment]
> The reason for search in workspaces is the scenario where a user spreads their windows to see what's open, doesn't have what they need, and can quickly launch it from there. We're unifying the launcher experience across the OS.

Either way my muscle memory is still very much GNOME oriented, so I welcome the change
