### ISSUE TITLE
Round edges on current workspace vs straight edges on unselected workspaces

### ISSUE THREAD

**Issue by spxak1** [pop-os/cosmic-workspaces#6]
Thanks for this great extension.

A minor aesthetic issue (maybe personal) is that the current workspace has the yellow border with rounded corners while the other workspaces have the standard rectangular shape.

Any thoughts on keeping the same shape for current and other workspaces? I like the rounded corners, others may feel otherwise. Maybe an option for that too in the extension options?

Thanks

**Comment by isantop** [comment]
Due to the way that the workspaces are drawn, the corners can't really be rounded without some significant drawing changes to the actual code (it's not a CSS change). The rounded corners for the currently active workspace are a result of drawing the border on top of the workspace and covering the border up (so, without having square edges on the current-workspace indicator, the corners of the current workspace will always be rounded to some degree).

**Comment by spxak1** [comment]
> Due to the way that the workspaces are drawn, the corners can't really be rounded without some significant drawing changes to the actual code (it's not a CSS change). The rounded corners for the currently active workspace are a result of drawing the border on top of the workspace and covering the border up (so, without having square edges on the current-workspace indicator, the corners of the current workspace will always be rounded to some degree).

Thanks for clearing this out. So does this mean that the most rectangular the current selection is, is rounder than the 3.38 version? 

This is an aesthetic issue so maybe not work the time and effort. For what it's worth, if all are rectangular, maybe the yellow selection should be as rectangular as possible. 

Thanks again.

**Comment by isantop** [comment]
Because it pertains to this discussion, the latest workspace picker styling has greatly reduced the amount that the active indicator is rounded, which helps minimize how noticeable this issue is:

![Image Pasted at 2021-10-13 10-27](https://user-images.githubusercontent.com/5883565/137360812-8d225d22-1147-4bcf-9741-56b422b7a073.png)

It seems there my be significant challenges in making the previews rounded because the wallpaper background for each widget (as well as all of the window previews on each workspace) is a separate widget.

**Comment by spxak1** [comment]
> Because it pertains to this discussion, the latest workspace picker styling has greatly reduced the amount that the active indicator is rounded, which helps minimize how noticeable this issue is:
> 
> ![Image Pasted at 2021-10-13 10-27](https://user-images.githubusercontent.com/5883565/137360812-8d225d22-1147-4bcf-9741-56b422b7a073.png)
> 
> It seems there my be significant challenges in making the previews rounded because the wallpaper background for each widget (as well as all of the window previews on each workspace) is a separate widget.

Thanks. This looks very nice. Is the transparency also a standard feature?

**Comment by isantop** [comment]
Yes, the picker is intended to be transparent.

**Comment by spxak1** [comment]
> Yes, the picker is intended to be transparent.

Looks great. Thank you.
